FROM alpine:latest

# Install
RUN apk add --no-cache py3-pip ansible bash openssh
RUN ansible-galaxy collection install community.general
RUN pip3 install jmespath

RUN mkdir /root/ansible

WORKDIR /root/ansible

ENV HOME /root/

CMD bash 
